net7_pundit_transformer_info:
    path:     /
    defaults: { _controller: Net7PunditTransformerBundle:Default:info }
    methods:   [GET]

net7_pundit_transformer_start:
    path:     /
    defaults: { _controller: Net7PunditTransformerBundle:Default:start }
    methods:   [POST]

net7_pundit_transformer_status:
    path:     /status/{token}
    defaults: { _controller: Net7PunditTransformerBundle:Default:status }
    methods:   [GET]

net7_pundit_transformer_vocabulary:
    path:     /vocabulary
    defaults: { _controller: Net7PunditTransformerBundle:Default:vocabulary}
    methods:   [GET]

net7_pundit_transformer_show:
    path:     /show/{token}
    defaults: { _controller: Net7PunditTransformerBundle:Default:show }
    methods:   [GET]

net7_pundit_transformer_view:
    path:     /view/{token}
    defaults: { _controller: Net7PunditTransformerBundle:Default:view }
    methods:   [GET]

net7_pundit_transformer_save_from_pundit:
    path:     /save_from_pundit
    defaults: { _controller: Net7PunditTransformerBundle:Default:saveFromPundit }
    methods:   [POST]


net7_pundit_config:
    path:     /pundit_config
    defaults: { _controller: Net7PunditTransformerBundle:Default:punditConfig }
    methods:   [GET]

net7_fusepool_config:
    path:     /fusepool/config/
    defaults: { _controller: Net7PunditTransformerBundle:Default:fusepoolConfig }
    methods:   [POST]
